import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const DEFAULT_SKILLS = [
  'JavaScript',
  'TypeScript',
  'Python',
  'React',
  'Node.js',
  'Next.js',
  'System Design',
  'Career Growth',
  'Leadership',
  'Communication',
  'Data Science',
  'Machine Learning',
  'DevOps',
  'AWS',
  'PostgreSQL',
  'Java',
  'C#',
  'Go',
  'Rust',
  'PHP',
  'Ruby',
  'Swift',
  'Kotlin',
  'Dart',
  'Flutter',
  'React Native',
  'Vue.js',
  'Angular',
  'Svelte',
  'jQuery',
  'Bootstrap',
  'Tailwind CSS',
  'CSS',
  'HTML',
  'GraphQL',
  'REST APIs',
  'Microservices',
  'Kubernetes',
  'Docker',
  'Terraform',
  'Ansible',
  'CI/CD',
  'Git',
  'GitHub Actions',
  'Jenkins',
  'Linux',
  'Nginx',
  'Redis',
  'MongoDB',
  'MySQL',
  'SQLite',
  'Elasticsearch',
  'Kafka',
  'RabbitMQ',
  'Python',
  'Django',
  'Flask',
  'FastAPI',
  'Express.js',
  'NestJS',
  'Spring Boot',
  '.NET Core',
  'Laravel',
  'Rails',
  'Firebase',
  'Supabase',
  'PlanetScale',
  'Google Cloud',
  'Azure',
  'Heroku',
  'Vercel',
  'Netlify',
  'Deep Learning',
  'NLP',
  'Computer Vision',
  'Data Engineering',
  'Snowflake',
  'Databricks',
  'Tableau',
  'Power BI',
  'Excel',
  'Statistics',
  'A/B Testing',
  'Product Management',
  'Agile',
  'Scrum',
  'Technical Writing',
  'Public Speaking',
  'Mentoring',
  'Team Building',
  'Conflict Resolution',
  'Time Management',
  'Interviewing',
  'Resume Review',
  'Salary Negotiation',
  'Startup Strategy',
  'Fundraising',
  'Marketing',
  'SEO',
  'Growth Hacking',
  'UI Design',
  'UX Research',
  'Figma',
  'Adobe XD',
  'Cybersecurity',
  'Penetration Testing',
  'Blockchain',
  'Solidity',
  'Smart Contracts',
  'IoT',
  'Embedded Systems',
  'Game Development',
  'Unity',
  'Unreal Engine',
  'AR/VR',
  'Quantum Computing',
  'Algorithms',
  'Data Structures',
  'Competitive Programming',
  'Technical Leadership',
];

async function main() {
  for (const name of DEFAULT_SKILLS) {
    await prisma.skill.upsert({
      where: { name },
      update: {},
      create: { name },
    });
  }
  console.log('Skills seeded');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
